const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const esc = x => String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => n==null||!Number.isFinite(n)?'—':Math.round(n).toLocaleString('ru-RU');
const exact = n => n==null||!Number.isFinite(n)?'—':n.toLocaleString('ru-RU',{maximumFractionDigits:2,minimumFractionDigits:2});
const percent = n => n==null||!Number.isFinite(n)?'—':(n*100).toLocaleString('ru-RU',{maximumFractionDigits:1})+'%';
const compact = n => n==null||!Number.isFinite(n)?'—':Math.abs(n)>=1e6?(n/1e6).toLocaleString('ru-RU',{maximumFractionDigits:2})+' млн':Math.abs(n)>=1e3?(n/1e3).toLocaleString('ru-RU',{maximumFractionDigits:0})+' тыс':money(n);
const sum = a => a.reduce((s,x)=>s+(typeof x==='number'&&Number.isFinite(x)?x:0),0);
const date = (x,long=false) => x?new Date(x.length===10?x+'T12:00:00Z':x).toLocaleDateString('ru-RU',{day:'numeric',month:long?'long':'short',...(long?{year:'numeric'}:{})}):'—';
const datetime = x => x?new Date(x).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})+' МСК':'—';
const months=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
const shortMonths=['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек'];
const C={blue:'#3fa9f5',light:'#b8ddf8',emerald:'#047857',amber:'#c6a36e',red:'#c00000',navy:'#0a1628',muted:'#667085'};
const tabDefs=[['overview','Свод','M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z'],['pnl','ОПиУ','M4 3h16v18H4z M4 9h16 M10 9v12 M4 15h16'],['cash','ДДС','M3 7h18v14H3z M3 7l13-4v4 M16 12h5v5h-5z'],['salary','Зарплаты','M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6 M16 11a3 3 0 1 0 0-6 M2 21v-3c0-5 12-5 12 0v3 M16 14c4 0 6 1 6 4v3'],['suppliers','Поставщики','M3 7l9-4 9 4-9 4z M3 7v11l9 4 9-4V7 M12 11v11'],['ttk','ТТК и фудкост','M4 3h16v18H4z M8 7h8 M8 11h2 M14 11h2 M8 15h2 M14 15h2 M8 19h2 M14 19h2']];
let D=null,sessionKey=null,sessionSalt=null,preview=false,currentExport=[],toastTimer;
const state={tab:'overview',entity:'network',pnlView:'board',months:{overview:8,pnl:8,cash:9,salary:9,suppliers:9,ttk:7},scopes:{overview:'month',pnl:'month',cash:'month',salary:'month',suppliers:'month',ttk:'month'},mode:'compare',salaryRole:'all',salarySearch:'',supplierType:'all',supplierStatus:'all',supplierSearch:'',ttkSearch:'',ttkView:'catalog',articleSearch:'',allArticles:false,page:1};
const icon = path => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${path}"/></svg>`;
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4200)}
function activeMonths(){let m=state.months[state.tab];return state.scopes[state.tab]==='ytd'?Array.from({length:m},(_,i)=>i+1):[m]}
function periodLabel(){let m=state.months[state.tab];return state.scopes[state.tab]==='ytd'?`Январь — ${months[m-1].toLowerCase()} ${D.year}`:`${months[m-1]} ${D.year}`}
function pnlValue(article,entity=state.entity,mm=activeMonths(),mode=state.mode){mode=['compare','previous'].includes(mode)?'actual':mode;let rows=D.pnl.rows.filter(r=>r.entity===entity&&r.article===String(article)&&mm.includes(r.month)&&r[mode==='plan'?'hasPlan':'hasActual']);return rows.length?sum(rows.map(r=>r[mode])):null}
function pnlRatio(article,entity=state.entity,mm=activeMonths(),mode=state.mode){let a=pnlValue(article,entity,mm,mode),b=pnlValue(37,entity,mm,mode);return a==null||!b?null:a/b}
function kpi(label,value,meta='',kind='',unit='₽'){return `<article class="kpi ${kind}"><div class="kpi-label">${esc(label)}</div><div class="kpi-value ${state.mode==='plan'&&kind!=='accent'&&/план/i.test(label)?'plan-value':''}">${esc(value)}${value!=='—'&&unit?`<small>${esc(unit)}</small>`:''}</div><div class="kpi-meta">${meta}</div></article>`}
function mini(label,value,meta,symbol){return `<article class="mini-card"><div class="mini-icon">${symbol}</div><div><div class="label">${esc(label)}</div><div class="value mono">${money(value)} ₽</div><div class="meta">${meta}</div></div></article>`}
function panel(title,subtitle,body,span='span6',tag=''){return `<section class="panel ${span}"><div class="panel-header"><div><h2>${esc(title)}</h2>${subtitle?`<p>${subtitle}</p>`:''}</div>${tag?`<span class="tag">${esc(tag)}</span>`:''}</div>${body}</section>`}
function empty(text){return `<div class="empty">${text}</div>`}
function delta(current,previous){if(current==null||previous==null||previous===0)return '<span>Нет сопоставимого периода</span>';const p=(current/previous-1);return `<span class="delta ${p>=0?'positive':'negative'}">${p>=0?'+':''}${percent(p)}</span> к прошлому месяцу`}
function heading(title,description,source){return `<div class="page-heading"><div><h1>${esc(title)}</h1><p>${description}</p></div><div class="updated">Источник обновлён<br><strong>${datetime(D.sources[source]?.modifiedAt)}</strong></div></div>`}
function controls({entity=true,mode=true,period=true}={}){return `<div class="filters">${period?`<div class="field"><label for="month">Период</label><select id="month">${months.map((m,i)=>`<option value="${i+1}" ${state.months[state.tab]===i+1?'selected':''}>${m} ${D.year}</option>`).join('')}</select></div>`:''}${entity?`<div class="field"><label for="entity">Периметр</label><select id="entity"><option value="network" ${state.entity==='network'?'selected':''}>Сеть целиком</option><option value="heroes" ${state.entity==='heroes'?'selected':''}>Героев</option><option value="kosinka" ${state.entity==='kosinka'?'selected':''}>Косинка</option></select></div>`:''}${mode?`<div class="field"><label for="presentation">Сравнение</label><select id="presentation">${[['compare','План ↔ факт'],['previous','Прошлый месяц'],['actual','Только факт'],['plan','Только план']].map(([v,l])=>`<option value="${v}" ${state.mode===v?'selected':''}>${l}</option>`).join('')}</select></div>`:''}${period?`<div class="field"><label for="scope-select">Расчёт</label><select id="scope-select"><option value="month" ${state.scopes[state.tab]==='month'?'selected':''}>За месяц</option><option value="ytd" ${state.scopes[state.tab]==='ytd'?'selected':''}>С начала года</option></select></div>`:''}<button class="button" id="export-button" title="Все строки текущего отчёта">↓ CSV</button></div>`}
function chartLegend(series){return `<div class="legend">${series.map(s=>`<span><i style="background:${s.color}"></i>${esc(s.label)}</span>`).join('')}</div>`}
function lineChart(series,labels,{height=238,unit='₽',cumulative=false}={}){
 const all=series.flatMap(s=>s.values).filter(v=>v!=null&&Number.isFinite(v));if(!all.length)return empty('За выбранный период нет данных.');
 const w=760,h=height,p={l:62,r:20,t:18,b:34};let max=Math.max(...all,0),min=Math.min(...all,0);if(max===min)max=min+1;const step=(max-min)/4;max+=step*.3;
 const x=i=>p.l+(w-p.l-p.r)*(labels.length<=1?.5:i/(labels.length-1)), y=v=>p.t+(h-p.t-p.b)*(1-(v-min)/(max-min));
 let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(series.map(s=>s.label).join(', '))}"><title>${esc(series.map(s=>s.label).join(', '))}</title>`;
 for(let i=0;i<=4;i++){const v=min+(max-min)*i/4;svg+=`<line class="axis" x1="${p.l}" y1="${y(v)}" x2="${w-p.r}" y2="${y(v)}"/><text x="${p.l-11}" y="${y(v)+4}" text-anchor="end">${esc(unit==='%'?percent(v):compact(v))}</text>`;}
 labels.forEach((l,i)=>svg+=`<text x="${x(i)}" y="${h-8}" text-anchor="middle">${esc(l)}</text>`);
 series.forEach(s=>{let started=false,d='';s.values.forEach((v,i)=>{if(v==null){started=false;return}d+=`${started?'L':'M'}${x(i)},${y(v)} `;started=true});svg+=`<path d="${d}" fill="none" stroke="${s.color}" stroke-width="3" stroke-linejoin="round" stroke-linecap="round" ${s.dashed?'stroke-dasharray="7 6"':''}/>`;s.values.forEach((v,i)=>{if(v!=null)svg+=`<circle class="chart-point" tabindex="0" cx="${x(i)}" cy="${y(v)}" r="4" fill="white" stroke="${s.color}" stroke-width="2.5"><title>${esc(labels[i])} · ${esc(s.label)}: ${unit==='%'?percent(v):money(v)+' '+unit}</title></circle>`})});
 return svg+'</svg>'+chartLegend(series);
}
function barChart(rows,series,{height=238,unit='₽'}={}){
 if(!rows.length)return empty('За выбранный период нет данных.');const w=760,h=height,p={l:66,r:18,t:12,b:35};const max=Math.max(...rows.map(r=>sum(series.map(s=>Math.max(r[s.key]??0,0)))),1)*1.15;const xstep=(w-p.l-p.r)/rows.length,bw=Math.min(50,xstep*.58),y=v=>h-p.b-(h-p.t-p.b)*v/max;
 let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(series.map(s=>s.label).join(', '))}"><title>${esc(series.map(s=>s.label).join(', '))}</title>`;
 for(let i=0;i<=4;i++){const v=max*i/4;svg+=`<line class="axis" x1="${p.l}" y1="${y(v)}" x2="${w-p.r}" y2="${y(v)}"/><text x="${p.l-10}" y="${y(v)+4}" text-anchor="end">${compact(v)}</text>`;}
 rows.forEach((r,i)=>{const x=p.l+xstep*(i+.5)-bw/2;let bottom=0;series.forEach(s=>{let v=r[s.key]??0;if(v>0){svg+=`<rect tabindex="0" class="chart-point" x="${x}" y="${y(bottom+v)}" width="${bw}" height="${Math.max(.5,y(bottom)-y(bottom+v))}" rx="2" fill="${s.color}"><title>${esc(r.label)} · ${esc(s.label)}: ${money(v)} ${unit}</title></rect>`;}bottom+=v});svg+=`<text x="${x+bw/2}" y="${h-8}" text-anchor="middle">${esc(r.label)}</text>`});return svg+'</svg>'+chartLegend(series);
}
function barList(rows,{color=C.blue,suffix='₽',maxRows=8}={}){if(!rows.length)return empty('Нет данных для сравнения.');const max=Math.max(...rows.map(r=>Math.abs(r.value)),1);return `<div class="bar-list">${rows.slice(0,maxRows).map(r=>`<div><div class="bar-label"><span title="${esc(r.label)}">${esc(r.label)}</span><span class="bar-value">${suffix==='%'?percent(r.value):money(r.value)+' '+suffix}</span></div><div class="bar-track"><i style="width:${Math.abs(r.value)/max*100}%;background:${r.color||color}"></i></div></div>`).join('')}</div>`}
function sourceLink(key,cell,label='Открыть в таблице'){const s=D.sources[key];const tabName=cell?.split('!')[0],range=cell?.split('!')[1];return `<a href="${esc(s.url)}${range?'#range='+encodeURIComponent(`'${tabName}'!${range}`):''}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`}
function modal(title,body){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;$('#detail-dialog').showModal()}
function coverageNote(){const mm=activeMonths(),rows=D.pnl.periods.filter(r=>r.entity===state.entity&&mm.includes(r.month)),fact=rows.filter(r=>r.hasActual).map(r=>shortMonths[r.month-1]),plan=rows.filter(r=>r.hasPlan).map(r=>shortMonths[r.month-1]);return `<div class="scope-note">${periodLabel()} · Факт: ${fact.join(', ')||'не заполнен'} · План: ${plan.join(', ')||'не заполнен'}${state.scopes[state.tab]==='ytd'?' · Суммируются только заполненные месяцы':''}. Деньги и текущие обязательства — на отдельную указанную дату.</div>`}
function trend(article,entity=state.entity){const periods=Array.from({length:12},(_,i)=>i+1);const cum=state.scopes[state.tab]==='ytd';return [{label:'Факт',color:C.blue,values:periods.map(m=>{let cur=pnlValue(article,entity,[m],'actual');return cur==null?null:cum?pnlValue(article,entity,periods.filter(x=>x<=m),'actual'):cur})},{label:'План',color:C.emerald,dashed:true,values:periods.map(m=>{let cur=pnlValue(article,entity,[m],'plan');return cur==null?null:cum?pnlValue(article,entity,periods.filter(x=>x<=m),'plan'):cur})}]}
function canCompare(mm,entity=state.entity,mode='plan',otherMonths=mm){
 const a=D.pnl.periods.filter(r=>r.entity===entity&&mm.includes(r.month)&&r.hasActual).map(r=>r.month).sort((a,b)=>a-b);
 const b=D.pnl.periods.filter(r=>r.entity===entity&&otherMonths.includes(r.month)&&r[mode==='plan'?'hasPlan':'hasActual']).map(r=>r.month+(mode==='actual'?1:0)).sort((a,b)=>a-b);
 return a.length>0&&a.length===b.length&&a.every((m,i)=>m===b[i]);
}
function overviewMetric(id,label,{ratio=false,less=false,icon='₽'}={}){
 const mode=state.mode==='plan'?'plan':'actual',mm=activeMonths();const value=ratio?pnlRatio(id,state.entity,mm,mode):pnlValue(id,state.entity,mm,mode);
 const compared=state.mode==='compare'||state.mode==='previous',otherMonths=state.mode==='previous'?mm.map(m=>m-1).filter(m=>m>0):mm,otherMode=state.mode==='previous'?'actual':'plan';
 const actual=ratio?pnlRatio(id,state.entity,mm,'actual'):pnlValue(id,state.entity,mm,'actual'),other=ratio?pnlRatio(id,state.entity,otherMonths,otherMode):pnlValue(id,state.entity,otherMonths,otherMode),fmt=ratio?percent:compact;
 let meta=ratio?'Доля в выручке':'₽ · '+periodLabel();
 if(compared){if(actual!=null&&other!=null&&!canCompare(mm,state.entity,otherMode,otherMonths)){meta='Разное покрытие месяцев'}else if(actual!=null&&other!=null&&(other!==0||ratio)){const diff=actual-other,positive=less?diff<=0:diff>=0;meta=`<span class="${positive?'positive':'negative'}">${diff>0?'+':''}${ratio?(diff*100).toLocaleString('ru-RU',{maximumFractionDigits:1})+' п.п.':percent(diff/Math.abs(other))}</span> ${otherMode==='plan'?'к плану':'к прошлому периоду'}`}else meta=actual==null?'Факт не заполнен':other===0?(actual===0?'Без изменения':'База сравнения равна нулю'):otherMode==='plan'?'Нет плана на этот период':'Нет предыдущего факта'}
 return `<article class="kpi plan-finance"><div class="kpi-label">${esc(label)}<span class="kpi-chip">${icon}</span></div>${compared?`<div class="dual-values"><div><small>Факт</small><b>${fmt(actual)}</b></div><div class="${otherMode==='plan'?'plan-col':''}"><small>${otherMode==='plan'?'План':'Ранее'}</small><b>${fmt(other)}</b></div></div>`:`<div class="kpi-value ${mode==='plan'?'plan-value':''}">${fmt(value)}${ratio||value==null?'':'<small>₽</small>'}</div>`}<div class="kpi-meta">${meta}</div></article>`;
}
function groupedChart(rows,series,{height=250,unit='₽',lines=[]}={}){
 const all=[...rows.flatMap(r=>series.map(s=>r[s.key])),...lines.flatMap(l=>l.values)].filter(x=>x!=null&&Number.isFinite(x));if(!all.length)return empty('За этот период нет заполненных данных.');
 const w=760,h=height,p={l:58,r:15,t:15,b:35},min=Math.min(0,...all),max=Math.max(1,...all)*1.12,ystep=(h-p.t-p.b)/(max-min),y=v=>p.t+(max-v)*ystep,step=(w-p.l-p.r)/rows.length,bw=Math.min(35,(step*.7)/Math.max(series.length,1));
 let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(series.map(s=>s.label).join(', '))}"><title>${esc(series.map(s=>s.label).join(', '))}</title>`;
 for(let i=0;i<=4;i++){const v=min+(max-min)*i/4;svg+=`<line class="axis" x1="${p.l}" x2="${w-p.r}" y1="${y(v)}" y2="${y(v)}"/><text x="${p.l-9}" y="${y(v)+4}" text-anchor="end">${unit==='%'?percent(v):compact(v)}</text>`}
 rows.forEach((r,i)=>{const center=p.l+step*(i+.5);series.forEach((s,j)=>{const v=r[s.key];if(v==null)return;const x=center+(j-series.length/2)*bw;svg+=`<rect class="chart-point" tabindex="0" x="${x}" y="${Math.min(y(v),y(0))}" width="${bw-3}" height="${Math.max(v===0?0:1,Math.abs(y(v)-y(0)))}" rx="3" fill="${s.color}"><title>${esc(r.label)} · ${esc(s.label)}: ${unit==='%'?percent(v):exact(v)+' '+unit}</title></rect>`});svg+=`<text x="${center}" y="${h-10}" text-anchor="middle">${esc(r.label)}</text>`});
 lines.forEach(l=>{let d='',started=false;l.values.forEach((v,i)=>{if(v==null){started=false;return}const x=p.l+step*(i+.5);d+=`${started?'L':'M'}${x},${y(v)} `;started=true;svg+=`<circle class="chart-point" tabindex="0" cx="${x}" cy="${y(v)}" r="3" fill="${l.color}"><title>${esc(rows[i].label)} · ${esc(l.label)}: ${exact(v)} ${unit}</title></circle>`});svg+=`<path d="${d}" stroke="${l.color}" stroke-width="2.5" fill="none" ${l.dashed?'stroke-dasharray="5 5"':''}/>`});return svg+'</svg>'+chartLegend([...series,...lines]);
}
function costDonut(){
 const rev=pnlValue(37),cogs=pnlValue(40),payroll=pnlValue(61),net=pnlValue(156);if(!rev||[cogs,payroll,net].some(x=>x==null))return empty('Нет данных для структуры выручки.');
 const rows=[{label:'Себестоимость',value:cogs,color:'#3fa9f5'},{label:'ФОТ',value:payroll,color:'#0a1628'},{label:'Прочие затраты',value:rev-cogs-payroll-net,color:'#c6bdaa'},{label:'Чистая прибыль',value:net,color:'#00a878'}];
 if(rows.some(r=>r.value<0))return barList(rows);
 let offset=0;const length=2*Math.PI*59;const circles=rows.map(r=>{const fraction=r.value/rev,part=length*fraction;const html=`<circle class="chart-point" tabindex="0" cx="90" cy="90" r="59" fill="none" stroke="${r.color}" stroke-width="25" stroke-dasharray="${part} ${length-part}" stroke-dashoffset="${-offset}"><title>${r.label}: ${exact(r.value)} ₽ · ${percent(fraction)}</title></circle>`;offset+=part;return html}).join('');
 return `<div class="donut-box"><svg viewBox="0 0 180 180" role="img" aria-label="Структура выручки"><g transform="rotate(-90 90 90)">${circles}</g><text x="90" y="89" text-anchor="middle" class="donut-center">${compact(rev)}</text><text x="90" y="105" text-anchor="middle" class="donut-sub">выручка, ₽</text></svg><div class="donut-labels">${rows.map(r=>`<div><i style="background:${r.color}"></i><span>${r.label}</span><b>${percent(r.value/rev)}</b></div>`).join('')}</div></div>`;
}
function ownerAttention(){
 const messages=[],month=state.months.overview,act=pnlValue(37,state.entity,activeMonths(),'actual'),plan=pnlValue(37,state.entity,activeMonths(),'plan');
 if(act==null)messages.push(['info','i',`<b>${months[month-1]}: факт ОПиУ не заполнен.</b> Прогноз показан отдельно, без нулевого «факта».`]);else if(plan==null)messages.push(['info','i','<b>План этого периода не заполнен.</b> Для динамики выберите «Прошлый месяц»; план источника начинается с сентября.']);
 const late=D.suppliers.invoices.filter(r=>!r.paid&&r.overdue);if(late.length)messages.push(['','!',`<b>${money(sum(late.map(r=>r.amount)))} ₽ — просроченные документы.</b> ${late.length} ${late.length===1?'накладная':'накладных'} с наступившим сроком. <button data-jump="suppliers">Открыть →</button>`]);
 if(D.salary.issues.length)messages.push(['','!',`<b>Зарплаты: ${D.salary.issues.length} записей на проверке.</b> Неоднозначные суммы отделены от долга. <button data-jump="salary">Посмотреть →</button>`]);
 const controls=D.pnl.checks.filter(c=>c.status&&c.status!=='OK');if(controls.length)messages.push(['','!',`<b>Контроли ОПиУ требуют внимания.</b> ${controls.map(c=>`${esc(c.label)}: ${exact(c.value)}`).join('; ')}. <button data-open-sources>Источник →</button>`]);
 const reconciled=D.cash.months.filter(m=>m.hasData).every(m=>Math.abs(m.reconciliation)<.01);if(reconciled)messages.push(['ok','✓','<b>ДДС сходится.</b> Остатки проверены по всем заполненным месяцам.']);
 return messages.slice(0,5).map(([cl,s,html])=>`<div class="owner-row"><i class="${cl}">${s}</i><p>${html}</p></div>`).join('');
}
function renderOverviewV2(){
 const cash=D.cash.months.filter(m=>m.hasData).at(-1),div=sum(D.cash.months.filter(m=>m.hasData).map(m=>m.dividends));const salaryDebt=sum(D.salary.payments.filter(r=>!r.paid).map(r=>r.amount)),supplierDebt=sum([...D.suppliers.weekly,...D.suppliers.invoices].filter(r=>!r.paid).map(r=>r.amount));
 const rev=pnlValue(37),prime=rev?(pnlValue(40)+pnlValue(61))/rev:null;
 const kpis=overviewMetric(37,'Выручка · период')+overviewMetric(54,'Валовая маржа',{ratio:true,icon:'%'})+overviewMetric(140,'EBITDA-маржа',{ratio:true,icon:'%'})+overviewMetric(156,'Чистая прибыль')+kpi('Деньги · все счета',compact(cash?.closing),`На ${date(cash?.lastDate)} · вся сеть<br>Файл ДДС: ${date(D.sources.dds.modifiedAt)}`)+kpi('PRIME Cost',percent(prime),'Себестоимость + ФОТ / выручка','','')+overviewMetric(40,'Себестоимость',{ratio:true,less:true,icon:'%'})+overviewMetric(61,'ФОТ / выручка',{ratio:true,less:true,icon:'%'})+overviewMetric(43,'Списания компании',{ratio:true,less:true,icon:'%'})+overviewMetric(53,'Порча',{ratio:true,less:true,icon:'%'})+kpi('Дивиденды · с января',compact(div),`ДДС по ${date(cash?.lastDate)} · вся сеть`)+kpi('Учтённые обязательства',compact(salaryDebt+supplierDebt),'Вся сеть · долг на дату снимка');
 const periods=Array.from({length:12},(_,i)=>i+1),tm=mode=>periods.map(m=>{const mm=state.scopes.overview==='ytd'?periods.filter(x=>x<=m):[m];return {label:shortMonths[m-1],revenue:pnlValue(37,state.entity,[m],mode)==null?null:pnlValue(37,state.entity,mm,mode),ebitda:pnlValue(37,state.entity,[m],mode)==null?null:pnlValue(140,state.entity,mm,mode)}}),actual=tm('actual'),plan=tm('plan');
 const rows=periods.map((m,i)=>({label:shortMonths[i],actual:actual[i].revenue,plan:plan[i].revenue}));
 const comparison=['heroes','kosinka'].map(entity=>({entity,label:entity==='heroes'?'Героев':'Косинка',revenue:pnlValue(37,entity),net:pnlValue(156,entity),margin:pnlRatio(156,entity),plan:pnlValue(37,entity,activeMonths(),'plan'),actual:pnlValue(37,entity,activeMonths(),'actual')}));
 const points=tableHTML([{label:'Точка',render:r=>`<button class="row-link" data-open-entity="${r.entity}">${r.label} ↗</button>`},{label:'Выручка',numeric:true,render:r=>compact(r.revenue)},{label:'Чистая',numeric:true,render:r=>compact(r.net)},{label:'Рент.',numeric:true,render:r=>percent(r.margin)}],comparison);
 const m=D.cash.months.filter(m=>m.hasData).map(m=>({label:shortMonths[m.month-1],inflow:m.inflow,outflow:-m.outflow,dividends:-m.dividends,closing:m.closing}));
 currentExport=D.pnl.articles.filter(a=>a.kind!=='section').map(a=>({Статья:a.label,Период:periodLabel(),Точка:state.entity,Единица:a.unit,Факт:displayArticle(a,state.entity,activeMonths(),'actual'),План:displayArticle(a,state.entity,activeMonths(),'plan')}));
 return heading('Период · Сводка','Финансовые результаты, деньги и обязательства на одном экране.','opiu')+controls()+coverageNote()+`<div class="kpi-grid overview-kpis">${kpis}</div><div class="grid">${panel('Выручка · план и факт · 2026',state.scopes.overview==='ytd'?'Накопительно с января · ₽':'По месяцам · ₽',groupedChart(rows,[{key:'actual',label:'Факт',color:C.blue},{key:'plan',label:'План',color:C.emerald}]),'span8','ОПиУ')}${panel('Что требует внимания','Проверки по реальным источникам',ownerAttention(),'span4')}${panel('Структура выручки','Себестоимость + ФОТ + прочее + прибыль',costDonut(),'span4','ОПиУ')}${panel('ОПиУ по точкам','Тот же период · ₽',points,'span4','ОПиУ')}${panel('Деньги и обязательства',`Вся сеть · деньги на ${date(cash?.lastDate)}`,`${cash?.wallets.filter(w=>w.closing).map(w=>`<div class="wallet-row"><span>${esc(w.name)}</span><b>${compact(w.closing)} ₽</b></div>`).join('')||''}<div class="wallet-row"><span>Долг по зарплатам</span><b>${compact(salaryDebt)} ₽</b></div><div class="wallet-row"><span>Долг поставщикам</span><b>${compact(supplierDebt)} ₽</b></div>`,'span4','ДДС / РЕЕСТРЫ')}${panel('Прибыль · план и факт','Чистая прибыль по месяцам · ₽',groupedChart(periods.map((m,i)=>({label:shortMonths[i],actual:pnlValue(37,state.entity,[m],'actual')==null?null:pnlValue(156,state.entity,state.scopes.overview==='ytd'?periods.filter(x=>x<=m):[m],'actual'),plan:pnlValue(37,state.entity,[m],'plan')==null?null:pnlValue(156,state.entity,state.scopes.overview==='ytd'?periods.filter(x=>x<=m):[m],'plan')})),[{key:'actual',label:'Факт',color:C.blue},{key:'plan',label:'План',color:C.emerald}]),'span6','ОПиУ')}${panel('ДДС · поступления, выплаты и остаток','Вся сеть · заполненные месяцы · ₽',groupedChart(m,[{key:'inflow',label:'Поступления',color:'#00a878'},{key:'outflow',label:'Выплаты',color:'#c78278'},{key:'dividends',label:'Дивиденды',color:'#c6bdaa'}],{lines:[{label:'Остаток',color:'#0a1628',values:m.map(x=>x.closing)}]}),'span6','ДДС')}</div>`;
}
function displayArticle(article,entity=state.entity,mm=activeMonths(),mode=state.mode){
 mode=['compare','previous'].includes(mode)?'actual':mode;
 if(article.kind!=='ratio')return pnlValue(article.id,entity,mm,mode);
 const rows=D.pnl.rows.filter(r=>r.entity===entity&&r.article===article.id&&mm.includes(r.month)&&r[mode==='plan'?'hasPlan':'hasActual']&&r[mode]!=null);
 const weights=rows.map(r=>({value:r[mode],weight:pnlValue(37,entity,[r.month],mode)}));const base=sum(weights.map(r=>r.weight));return base?sum(weights.map(r=>r.value*r.weight))/base:null;
}
function subnav(items,key){return `<div class="view-tabs" role="group" aria-label="Вид отчёта">${items.map(([v,l])=>`<button data-view-key="${key}" data-view="${v}" class="${state[key]===v?'active':''}">${esc(l)}</button>`).join('')}</div>`}
function tableHTML(columns,rows,{classes='',emptyText='По выбранным условиям нет записей.'}={}){return rows.length?`<div class="table-wrap"><table class="data-table ${classes}"><thead><tr>${columns.map(c=>`<th class="${c.numeric?'number':''}">${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${columns.map(c=>`<td class="${c.numeric?'number':''}">${c.render?c.render(r):esc(r[c.key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty(emptyText)}
function pages(rows,size=40){const count=Math.max(1,Math.ceil(rows.length/size));state.page=Math.min(state.page,count);return {rows:rows.slice((state.page-1)*size,state.page*size),footer:`<div class="pagination"><span>${rows.length?`${(state.page-1)*size+1}–${Math.min(state.page*size,rows.length)} из ${money(rows.length)}`:'0 записей'}</span><div><button class="button quiet" data-page="${state.page-1}" ${state.page===1?'disabled':''}>← Назад</button><span>${state.page} / ${count}</span><button class="button quiet" data-page="${state.page+1}" ${state.page===count?'disabled':''}>Дальше →</button></div></div>`}}
function searchInput(key,label){return `<input type="search" data-search="${key}" aria-label="${esc(label)}" placeholder="${esc(label)}" value="${esc(state[key])}">`}
function stateSelect(key,label,options){return `<div class="field"><label for="${key}">${esc(label)}</label><select id="${key}" data-state="${key}">${options.map(([v,l])=>`<option value="${esc(v)}" ${state[key]===v?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`}
function groupSum(rows,key,value){const m=new Map();for(const r of rows){const k=key(r);m.set(k,(m.get(k)||0)+value(r))}return [...m].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value)}
function matchEntity(site){return state.entity==='network'||site===(state.entity==='heroes'?'Героев':'Косинка')}
function issueBox(issues,key){return issues.length?`<details class="issues"><summary>Требует проверки · ${issues.length}</summary><div>${issues.map(i=>`<p class="small"><b>${esc(i.title)}</b>${i.amount!=null?' · '+money(i.amount)+' ₽':''}<br>${esc(i.detail)}<br>${sourceLink(key,i.cell,i.cell)}</p>`).join('')}</div></details>`:''}

function renderPnl(){
 const title=state.entity==='network'?'ОПиУ сети':`ОПиУ · ${state.entity==='heroes'?'Героев':'Косинка'}`;
 const header=heading(title,'Начисления, расходы и прибыль. План и факт остаются значениями исходного отчёта.','opiu')+controls({mode:state.pnlView!=='table'})+subnav([['board','Дашборд'],['table','Подробный ОПиУ']],'pnlView')+coverageNote();
 const exportRow=a=>({Статья:a.label,Единица:a.unit,Период:periodLabel(),План:displayArticle(a,state.entity,activeMonths(),'plan'),Факт:displayArticle(a,state.entity,activeMonths(),'actual')});
 if(state.pnlView==='table'){
  const all=Array.from({length:12},(_,i)=>i+1),query=state.articleSearch.toLocaleLowerCase('ru');
  const articles=D.pnl.articles.filter(a=>(!query||a.label.toLocaleLowerCase('ru').includes(query))&&(state.allArticles||a.kind==='section'||D.pnl.rows.some(r=>r.entity===state.entity&&r.article===a.id&&(r.hasActual&&r.actual||r.hasPlan&&r.plan))));
  currentExport=articles.filter(a=>a.kind!=='section').map(a=>{const r=exportRow(a);all.forEach(m=>{let mm=state.scopes.pnl==='ytd'?all.filter(x=>x<=m):[m];r[`${shortMonths[m-1]} План`]=displayArticle(a,state.entity,mm,'plan');r[`${shortMonths[m-1]} Факт`]=displayArticle(a,state.entity,mm,'actual')});return r});
  const columns=[{label:'Выбранный период',mm:activeMonths()},...all.map(m=>({label:months[m-1],mm:state.scopes.pnl==='ytd'?all.filter(x=>x<=m):[m],month:m}))];
  const t=`<div class="pnl-wrap table-wrap" tabindex="0" aria-label="ОПиУ, прокрутка по месяцам"><table class="data-table pnl-table"><thead><tr><th class="sticky" rowspan="2">Статья / показатель</th>${columns.map(c=>`<th colspan="3" class="${c.month===state.months.pnl?'selected-month':''}">${c.label}</th>`).join('')}</tr><tr>${columns.map(()=>'<th class="number plan">План</th><th class="number">Факт</th><th class="number">Факт − план</th>').join('')}</tr></thead><tbody>${articles.map(a=>`<tr class="${a.kind}"><td class="sticky">${esc(a.label)}${a.kind==='included'?'<span class="secondary">Уже включено в расходы</span>':''}</td>${a.kind==='section'?`<td colspan="${columns.length*3}"></td>`:columns.map(c=>{const p=displayArticle(a,state.entity,c.mm,'plan'),f=displayArticle(a,state.entity,c.mm,'actual'),d=p!=null&&f!=null&&canCompare(c.mm)?f-p:null;const fmt=a.kind==='ratio'?percent:money;return `<td class="number plan">${fmt(p)}</td><td class="number">${fmt(f)}</td><td class="number muted">${d==null?'—':a.kind==='ratio'?((d*100).toLocaleString('ru-RU',{maximumFractionDigits:1})+' п.п.'):money(d)}</td>`}).join('')}</tr>`).join('')}</tbody></table></div>`;
  return header+`<div class="table-toolbar">${searchInput('articleSearch','Найти статью')}<label class="small muted"><input type="checkbox" id="all-articles" ${state.allArticles?'checked':''}> Показывать пустые статьи</label><span class="table-meta">₽ · проценты — отдельно · ${state.scopes.pnl==='ytd'?'каждый месяц накопительно':'помесячно'}</span></div>`+t+`<p class="small muted table-foot">Статьи и заголовки закреплены. Проценты за несколько месяцев взвешены по выручке. «—» — нет заполненного периода; это не ноль. Отсутствующий план не подменяется фактом. Отклонение показано только при одинаковом месячном покрытии.</p>`;
 }
 const costIds=[57,61,68,81,87,97,114,118],costs=costIds.map(id=>({label:D.pnl.articles.find(a=>+a.id===id)?.label,value:pnlValue(id)})).filter(r=>r.value>0).sort((a,b)=>b.value-a.value);
 currentExport=D.pnl.articles.filter(a=>a.kind!=='section').map(exportRow);
 const major=[37,40,54,130,140,142,154,156].map(id=>{const a=D.pnl.articles.find(a=>+a.id===id);return {label:a?.label,plan:pnlValue(id,state.entity,activeMonths(),'plan'),actual:pnlValue(id,state.entity,activeMonths(),'actual')}});
 return header+`<div class="kpi-grid">${overviewMetric(37,'Выручка')}${overviewMetric(54,'Валовая прибыль')}${overviewMetric(140,'EBITDA после АУП')}${overviewMetric(156,'Чистая прибыль')}</div><div class="grid">${panel('Выручка и её план','Сохраняется выбранный режим накопления',lineChart(trend(37),shortMonths),'span8')}${panel('Структура операционных расходов','Крупные группы · без повторного прибавления АУП',barList(costs),'span4')}${panel('План и факт рядом',periodLabel(),tableHTML([{label:'Показатель',key:'label'},{label:'План, ₽',numeric:true,render:r=>`<span class="plan-value">${money(r.plan)}</span>`},{label:'Факт, ₽',numeric:true,render:r=>money(r.actual)},{label:'Отклонение, ₽',numeric:true,render:r=>r.actual!=null&&r.plan!=null&&canCompare(activeMonths())?money(r.actual-r.plan):'—'}],major),'span7')}${panel('Рентабельность чистой прибыли','Отношение чистой прибыли к выручке',lineChart(trend(156).map(s=>({...s,values:s.values.map((v,i)=>{const rr=trend(37).find(x=>x.label===s.label).values[i];return v!=null&&rr?v/rr:null})})),shortMonths,{unit:'%'}),'span5')}</div><div class="note">План отмечен изумрудным. Кредит показывается внутри CAPEX по исходной модели; его отражение в ОПиУ здесь не переинтерпретируется. <button data-pnl-table>Открыть все статьи →</button></div>`;
}

function cashRows(){return D.cash.transactions.filter(r=>activeMonths().includes(r.month))}
function renderCash(){
 const rows=cashRows(),ms=D.cash.months.filter(r=>r.hasData&&activeMonths().includes(r.month)),first=ms[0],last=ms.at(-1),inflow=sum(ms.map(r=>r.inflow)),outflow=sum(ms.map(r=>r.outflow)),div=sum(ms.map(r=>r.dividends));
 const dayMap=groupSum(rows,r=>r.date,r=>r.amount).sort((a,b)=>a.label.localeCompare(b.label));let running=first?.opening||0;const daily=dayMap.map(r=>({date:r.label,balance:running+=r.value}));
 const expenses=groupSum(rows.filter(r=>r.amount<0&&r.type==='operating'),r=>r.article,r=>-r.amount);
 const monthly=D.cash.months.filter(m=>m.hasData&&m.month<=state.months.cash).map(m=>{const mm=state.scopes.cash==='ytd'?D.cash.months.filter(x=>x.hasData&&x.month<=m.month):[m];return {label:shortMonths[m.month-1],inflow:sum(mm.map(x=>x.inflow)),outflow:sum(mm.map(x=>x.outflow))}});
 currentExport=rows.map(r=>({Дата:r.date,Кошелёк:r.wallet,Статья:r.article,Сумма:r.amount,Тип:r.type,Ячейка:r.sourceCell}));
 const filter=state.cashSearch||'',filtered=rows.filter(r=>`${r.article} ${r.wallet}`.toLocaleLowerCase('ru').includes(filter.toLocaleLowerCase('ru'))).sort((a,b)=>b.date.localeCompare(a.date)),p=pages(filtered);
 if(filter)currentExport=filtered.map(r=>({Дата:r.date,Кошелёк:r.wallet,Статья:r.article,Сумма:r.amount,Тип:r.type,Ячейка:r.sourceCell}));
 const ledger=tableHTML([{label:'Дата',render:r=>date(r.date)},{label:'Статья',render:r=>`${esc(r.article)}${r.type==='transfer'?'<div class="secondary">Перевод между кошельками</div>':''}`},{label:'Кошелёк',key:'wallet'},{label:'Движение, ₽',numeric:true,render:r=>`<span class="${r.amount<0?'':'positive'}">${r.amount>0?'+':''}${exact(r.amount)}</span>`},{label:'Источник',render:r=>sourceLink('dds',r.sourceCell,'Строка')}],p.rows)+p.footer;
 const checks=tableHTML([{label:'Месяц',render:r=>months[r.month-1]},{label:'Начало, ₽',numeric:true,render:r=>money(r.opening)},{label:'Все движения, ₽',numeric:true,render:r=>money(r.net)},{label:'Конец, ₽',numeric:true,render:r=>money(r.closing)},{label:'Расхождение, ₽',numeric:true,render:r=>`<span class="${Math.abs(r.reconciliation)<.01?'positive':'negative'}">${exact(r.reconciliation)}</span>`}],ms);
 return heading('Движение денег','Поступления, выплаты, дивиденды и остатки. Только денежные операции из регистра.','dds')+controls({entity:false,mode:false})+`<div class="scope-note">Заполнены: ${ms.map(m=>shortMonths[m.month-1]).join(' · ')||'нет данных'} · Последняя операция во всём ДДС: ${date(D.sources.dds.lastOperationDate,true)}</div><div class="kpi-grid">${kpi('Остаток на конец периода',money(last?.closing),last?`На ${date(last.lastDate)} · не суммируется по месяцам`:'Период не заполнен','accent')}${kpi('Операционные поступления',ms.length?money(inflow):'—','Без внутренних переводов и корректировок')}${kpi('Операционные выплаты',ms.length?money(outflow):'—','Без дивидендов и внутренних переводов')}${kpi('Забрано дивидендов',ms.length?money(div):'—',periodLabel())}</div><div class="grid">${panel('Деньги на конец дня','Остаток на начало + все движения · ₽',lineChart([{label:'Остаток',color:C.blue,values:daily.map(x=>x.balance)}],daily.map((x,i)=>i===0||i===daily.length-1||i%Math.ceil(daily.length/6)===0?date(x.date):'')),'span8')}${panel('Остатки по кошелькам',last?`На ${date(last.lastDate)}`:'Нет данных',last?last.wallets.map(w=>`<div class="wallet-row"><span>${esc(w.name)}</span><b>${money(w.closing)} ₽</b></div>`).join(''):empty('Период не заполнен.'),'span4')}${panel('Поступления и выплаты',state.scopes.cash==='ytd'?'Каждый столбец — накопление с начала года':'Каждый столбец — отдельный месяц',groupedChart(monthly.map(m=>({...m,outflow:-m.outflow})),[{key:'inflow',label:'Поступления',color:'#00a878'},{key:'outflow',label:'Выплаты',color:'#c78278'}]),'span7')}${panel('На что уходят деньги','Операционные выплаты · выбранный период',barList(expenses,{maxRows:8}),'span5')}${panel('Контроль денежных остатков','Начало + все движения = конец. Переводы и дивиденды учтены в сверке.',checks,'span12')}${panel('Регистр операций','В выгрузку попадают все найденные строки, не только текущая страница.',`<div class="table-toolbar">${searchInput('cashSearch','Найти статью или кошелёк')}<span class="table-meta">${money(filtered.length)} операций · ${periodLabel()}</span></div>`+ledger,'span12')}</div><div class="note">Дата изменения файла, дата последней операции и время загрузки различаются. Роялти и комиссия сайта в этом разделе показаны только при наличии платежа, а не расчётного начисления.</div>`;
}

function salaryRows(){return D.salary.payments.filter(r=>activeMonths().includes(r.month)&&matchEntity(r.site)&&(state.salaryRole==='all'||r.role===state.salaryRole)&&r.name.toLocaleLowerCase('ru').includes(state.salarySearch.toLocaleLowerCase('ru')))}
function salaryPeople(rows){const map=new Map();for(const r of rows){const p=map.get(r.personKey)||{key:r.personKey,name:r.name,role:r.role,site:r.site,total:0,paid:0,debt:0,weeks:0,last:r.periodEnd};p.total+=r.amount;p[r.paid?'paid':'debt']+=r.amount;p.weeks++;if(p.last<r.periodEnd)p.last=r.periodEnd;map.set(r.personKey,p)}return [...map.values()].sort((a,b)=>b.debt-a.debt||b.total-a.total)}
function renderSalary(){
 const rows=salaryRows(),people=salaryPeople(rows),total=sum(rows.map(r=>r.amount)),paid=sum(rows.filter(r=>r.paid).map(r=>r.amount)),debt=total-paid;
 const chartRows=activeMonths().map(m=>{const rr=rows.filter(r=>r.month===m);return {label:shortMonths[m-1],paid:sum(rr.filter(r=>r.paid).map(r=>r.amount)),debt:sum(rr.filter(r=>!r.paid).map(r=>r.amount)),count:rr.length}}).filter(r=>r.count);
 currentExport=people.map(r=>({Имя:r.name,Роль:r.role,Точка:r.site,Период:periodLabel(),Начислено:r.total,Выплачено:r.paid,'К выплате':r.debt,ПоследняяНеделя:r.last}));const p=pages(people);
 const table=tableHTML([{label:'Сотрудник',render:r=>`<button class="row-link" data-person="${esc(r.key)}">${esc(r.name)} ↗</button><div class="secondary">${esc(r.role)} · ${esc(r.site)}</div>`},{label:'Обещано всего, ₽',numeric:true,render:r=>money(r.total)},{label:'Выплачено, ₽',numeric:true,render:r=>`<span class="positive">${money(r.paid)}</span>`},{label:'К выплате, ₽',numeric:true,render:r=>`<b class="${r.debt?'negative':'muted'}">${money(r.debt)}</b>`},{label:'Последняя неделя',render:r=>date(r.last)}],p.rows)+p.footer;
 return heading('Зарплаты','Сколько обещано, сколько выплатили и кому осталось заплатить.','salary')+controls({mode:false})+`<div class="table-toolbar">${stateSelect('salaryRole','Команда',[['all','Все роли'],['Повара','Повара'],['Курьеры','Курьеры'],['Админы','Админы']])}${searchInput('salarySearch','Найти сотрудника')}<span class="table-meta">Имена объединены только по регистру и пробелам</span></div><div class="kpi-grid">${kpi('Обещано за период',money(total),'Недельные итоги разложены по месяцам')}${kpi('Выплачено',money(paid),`Закрыто ${total?percent(paid/total):'—'} обещанных сумм`)}${kpi('Учтённый долг',money(debt),`${D.salary.issues.length} записей на отдельной проверке`,'accent')}${kpi('Сотрудники в выборке',money(people.length),'Учёт отдельно по роли и точке','','')}</div><div class="grid">${panel('Выплаты и открытые обязательства','По календарному месяцу смен · статус недельного итога',barChart(chartRows,[{key:'paid',label:'Выплачено',color:C.emerald},{key:'debt',label:'К выплате',color:C.amber}]),'span8')}${panel('Кому осталось заплатить','Учтённый долг за выбранный период',barList(people.filter(p=>p.debt>0).map(p=>({label:`${p.name} · ${p.site}`,value:p.debt})),{color:C.amber}),'span4')}${panel('Выплаты по людям',`${periodLabel()} · нажмите на имя для расчётных недель`,table,'span12')}</div>`+issueBox(D.salary.issues,'salary')+`<div class="note">Зелёный недельный итог — выплачено, незелёный — обещано. Переходящие недели распределяются по календарным месяцам пропорционально дневным значениям, без изменения общей суммы. Текстовые пометки о долгах и залогах не прибавляются к итогам. ${D.decisions.correctSalaryTransition?'Первая неделя года приведена к 29.12.2025–04.01.2026 только в аналитике; доля января выделена по дневным суммам.':'Первая неделя блока «2026» с противоречивыми датами исключена до подтверждения.'} Администраторы без указанной точки остаются нераспределёнными.</div>`;
}
function openPerson(key){const rows=salaryRows().filter(r=>r.personKey===key).sort((a,b)=>b.periodEnd.localeCompare(a.periodEnd)),p=salaryPeople(rows)[0];if(!p)return;modal(`${p.name} · ${p.role} · ${p.site}`,`<div class="detail-kpis">${kpi('Обещано',money(p.total),periodLabel())}${kpi('Выплачено',money(p.paid))}${kpi('К выплате',money(p.debt))}</div>`+tableHTML([{label:'Расчётная неделя',render:r=>`${date(r.periodStart)} — ${date(r.periodEnd)}${r.monthlySplit?'<div class="secondary">Часть недели · полный итог '+money(r.sourceAmount)+' ₽</div>':''}`},{label:'Сумма, ₽',numeric:true,render:r=>exact(r.amount)},{label:'Статус',render:r=>`<span class="status ${r.paid?'paid':'debt'}">${r.paid?'Выплачено':'К выплате'}</span>`},{label:'Источник',render:r=>sourceLink('salary',r.sourceCell,r.sourceCell)}],rows)+`<div class="dialog-actions"><button class="button" id="detail-export">↓ Выгрузить недели</button></div>`);$('#detail-export').onclick=()=>exportCSV(rows.map(r=>({Имя:r.name,Роль:r.role,Точка:r.site,Начало:r.periodStart,Конец:r.periodEnd,Сумма:r.amount,Статус:r.paid?'Выплачено':'К выплате',Ячейка:r.sourceCell})),'salary-detail')}

function supplierBase(){return [...D.suppliers.weekly.map(r=>({...r,type:'ayk',supplier:'АЙК',document:'Недельный итог'})),...D.suppliers.invoices.map(r=>({...r,type:'manufacturer'}))].filter(r=>(state.supplierType==='all'||r.type===state.supplierType)&&`${r.supplier} ${r.document}`.toLocaleLowerCase('ru').includes(state.supplierSearch.toLocaleLowerCase('ru')))}
function renderSuppliers(){
 const all=supplierBase(),current=all.filter(r=>r.date.startsWith(String(D.year))),rows=current.filter(r=>activeMonths().includes(r.month)),debts=current.filter(r=>!r.paid),legacy=all.filter(r=>!r.paid&&r.date<String(D.year)),debt=sum(debts.map(r=>r.amount)),old=sum(legacy.map(r=>r.amount)),paid=sum(rows.filter(r=>r.paid).map(r=>r.amount));
 const selected=rows.filter(r=>state.supplierStatus==='all'||state.supplierStatus==='paid'&&r.paid||state.supplierStatus==='debt'&&!r.paid||state.supplierStatus==='overdue'&&r.overdue).sort((a,b)=>b.date.localeCompare(a.date));const p=pages(selected);
 const cols=[{label:'Дата / документ',render:r=>`${date(r.date)}<div class="secondary">${esc(r.document)}</div>`},{label:'Поставщик',render:r=>`<button class="row-link" data-supplier-row="${r.id}">${esc(r.supplier)} ↗</button>`},{label:'Сумма, ₽',numeric:true,render:r=>exact(r.amount)},{label:'Оплатить до',render:r=>date(r.due)},{label:'Статус',render:r=>`<span class="status ${r.paid?'paid':r.overdue?'overdue':'debt'}">${r.paid?'Оплачено':r.overdue?'Просрочено':'Не оплачено'}</span>`}];
 currentExport=selected.map(r=>({Дата:r.date,Поставщик:r.supplier,Документ:r.document,Сумма:r.amount,Срок:r.due,Статус:r.paid?'Оплачено':'Не оплачено',Ячейка:r.sourceCell}));
 const series=activeMonths().map(m=>{const rr=rows.filter(r=>r.month===m);return {label:shortMonths[m-1],paid:sum(rr.filter(r=>r.paid).map(r=>r.amount)),debt:sum(rr.filter(r=>!r.paid).map(r=>r.amount)),count:rr.length}}).filter(r=>r.count);
 const overdue=sum(debts.filter(r=>r.overdue).map(r=>r.amount));const soon=sum(debts.filter(r=>r.due&&r.due>=D.asOf&&((new Date(r.due)-new Date(D.asOf))/864e5)<=7).map(r=>r.amount));
 return heading('Поставщики','АЙК отдельно, документы производителей отдельно. Статус оплаты — по цвету суммы в таблице.','suppliers')+controls({entity:false,mode:false})+`<div class="table-toolbar">${stateSelect('supplierType','Реестр',[['all','Все поставщики'],['ayk','АЙК · товар'],['manufacturer','От производителя']])}${searchInput('supplierSearch','Найти поставщика или документ')}</div><div class="kpi-grid">${kpi('Долг по документам 2026',money(debt),`На ${date(D.asOf)} · весь 2026, независимо от периода`,'accent')}${kpi('Оплачено по документам периода',money(paid),periodLabel())}${kpi('Просрочено · 2026',money(overdue),'Только документы с указанным сроком')}${kpi('Оплатить в ближайшие 7 дней',money(soon),'От даты снимка')}</div><div class="mini-grid">${mini('АЙК · текущий долг',sum(debts.filter(r=>r.type==='ayk').map(r=>r.amount)),'В выбранном реестре и поиске','□')}${mini('Производители · текущий долг',sum(debts.filter(r=>r.type==='manufacturer').map(r=>r.amount)),'В выбранном реестре и поиске','≡')}${mini('Не оплачено по документам периода',sum(rows.filter(r=>!r.paid).map(r=>r.amount)),periodLabel(),'↔')}</div><div class="grid">${panel('Документы по месяцам','Оплаченные и открытые суммы · по дате документа, не дате платежа',barChart(series,[{key:'paid',label:'Оплачено',color:C.emerald},{key:'debt',label:'Не оплачено',color:C.amber}]),'span8')}${panel('Структура текущего долга','Документы 2026 · выбранный реестр и поиск',barList(groupSum(debts,r=>r.supplier,r=>r.amount),{color:C.amber}),'span4')}${panel('Документы и недельные итоги',`${periodLabel()} · ${money(selected.length)} записей`,`<div class="table-toolbar">${stateSelect('supplierStatus','Статус',[['all','Все статусы'],['paid','Оплачено'],['debt','Не оплачено'],['overdue','Просрочено']])}<span class="table-meta">Нажмите поставщика для деталей</span></div>`+tableHTML(cols,p.rows)+p.footer,'span12')}</div>`+(legacy.length?`<details><summary>Старые неоплаченные записи · ${money(old)} ₽</summary><div>${tableHTML(cols,legacy)}</div></details>`:'')+issueBox(D.suppliers.issues,'suppliers')+`<div class="note">АЙК считается один раз по итоговой сумме недели: промежуточные суммы точек не прибавляются повторно. На графиках — документы 2026 года. Остаток долга — состояние цветовых отметок на дату загрузки, исторический долг на конец прошлых месяцев из этих данных восстановить нельзя.</div>`;
}
function openSupplier(id){const r=supplierBase().find(r=>r.id===id);if(!r)return;modal(r.type==='ayk'?'АЙК · итог недели':r.supplier,`<div class="detail-kpis">${kpi('Сумма документа',money(r.amount))}${kpi('Статус',r.paid?'Оплачено':'Не оплачено','','','')}${kpi('Дата',date(r.date),'','','')}</div><p class="small">${esc(r.document)}${r.due?' · Срок оплаты '+date(r.due,true):''}</p>`+(r.breakdown?.length?tableHTML([{label:'Точка',key:'site'},{label:'Часть итога, ₽',numeric:true,render:x=>exact(x.amount)}],r.breakdown):'')+`<p class="small table-foot">${sourceLink('suppliers',r.sourceCell,r.sourceCell)}</p><div class="note">Статус взят из заливки суммы: зелёная — оплачено. Дата оплаты не подменяет цветовую отметку.</div>`)}

function renderTtk(){
 const q=state.ttkSearch.toLocaleLowerCase('ru'),dishes=D.ttk.dishes.filter(r=>r.name.toLocaleLowerCase('ru').includes(q)),sales=D.ttk.sales.filter(r=>activeMonths().includes(r.month)&&matchEntity(r.site)&&r.name.toLocaleLowerCase('ru').includes(q));
 const title=heading('ТТК и фудкост','Себестоимость порций, состав рецептур и покрытие продаж технологическими картами.','ttk')+subnav([['catalog','Каталог и рецептуры'],['sales','Фудкост продаж'],['checks','Качество ТТК']],'ttkView')+controls({entity:state.ttkView==='sales',mode:false,period:state.ttkView==='sales'})+`<div class="table-toolbar">${searchInput('ttkSearch','Найти блюдо')}<span class="table-meta">Каталог рассчитан по текущим ценам источника</span></div>`;
 if(state.ttkView==='sales'){
  const totalQty=sum(sales.map(r=>r.quantity)),covered=sales.filter(r=>r.unitCost!=null&&r.cost!=null&&!/НЕТ|НЕ НАЙ|ОШИБ/i.test(r.status)),cost=sum(covered.map(r=>r.cost)),qty=sum(covered.map(r=>r.quantity));const p=pages([...sales].sort((a,b)=>(b.cost||0)-(a.cost||0)));
  currentExport=sales.map(r=>({Дата:r.date,Точка:r.site,Блюдо:r.name,Количество:r.quantity,'Себестоимость порции':r.unitCost,'Нормативная себестоимость':r.cost,Статус:r.status}));
  return title+`<div class="kpi-grid">${kpi('Нормативная себестоимость',money(cost),'Только продажи с найденной ТТК','accent')}${kpi('Продано порций',money(totalQty),'По загруженному периоду','','шт.')}${kpi('Покрытие по количеству',percent(totalQty?qty/totalQty:null),'Порции с рассчитанной себестоимостью','','')}${kpi('Без рассчитанной ТТК',money(sales.length-covered.length),'Строки продаж, не нулевая себестоимость','','')}</div><div class="note amber">В источнике продаж нет цены продажи и выручки по блюду. Поэтому маржа и фудкост в процентах здесь не выдумываются. Нормативная себестоимость рассчитана по текущей версии цен, а не по исторической закупочной цене. Загружены: ${D.sources.ttk.coverage.join(', ')}.</div><div class="grid">${panel('Вклад блюд в себестоимость','Топ-10 по нормативным затратам',barList(groupSum(covered,r=>r.name,r=>r.cost),{maxRows:10}),'span6')}${panel('Объём продаж','Топ-10 по количеству порций',barList(groupSum(sales,r=>r.name,r=>r.quantity),{maxRows:10,suffix:'шт.',color:C.navy}),'span6')}${panel('Продажи и расчёт фудкоста',periodLabel(),tableHTML([{label:'Блюдо',key:'name'},{label:'Точка',key:'site'},{label:'Порции',numeric:true,render:r=>money(r.quantity)},{label:'Порция, ₽',numeric:true,render:r=>exact(r.unitCost)},{label:'Всего, ₽',numeric:true,render:r=>exact(r.cost)},{label:'Статус',key:'status'}],p.rows)+p.footer,'span12')}</div>`;
 }
 if(state.ttkView==='checks'){
  const checks=D.ttk.checks.filter(r=>r.name.toLocaleLowerCase('ru').includes(q));currentExport=checks.map(r=>({Блюдо:r.name,Проверка:r.type,Статус:r.status,Варианты:r.variants,Различия:r.different}));const p=pages(checks);
  return title+`<div class="kpi-grid">${kpi('Карты в актуальном каталоге',money(D.ttk.summary.cards),'Включая вложенные карты','','')}${kpi('Строки рецептур',money(D.ttk.summary.rows),'Загруженные строки с ингредиентом','','')}${kpi('Различающиеся варианты',money(D.ttk.summary.conflicts),'По листу проверок','','')}${kpi('Карты в старой сводке',money(D.ttk.summary.sourceSummaryCards),'Сводка источника отстаёт от каталога','','')}</div><div class="note amber">В источнике сводка указывает ${money(D.ttk.summary.sourceSummaryCards)} карт, а фактический каталог содержит ${money(D.ttk.summary.cards)}. Кабинет считает каталог полностью. Различающиеся версии ТТК не исправляются автоматически: используется выбранная версия из отчёта.</div>`+panel('Проверки технологических карт','Список из источника, без самостоятельной замены рецептур',tableHTML([{label:'Блюдо',key:'name'},{label:'Проверка',key:'type'},{label:'Статус',key:'status'},{label:'Вариантов',numeric:true,render:r=>money(r.variants)},{label:'Различаются',key:'different'},{label:'Источник',render:r=>sourceLink('ttk',r.sourceCell,'Проверка')}],p.rows)+p.footer,'span12');
 }
 currentExport=dishes.map(r=>({ID:r.id,Блюдо:r.name,'Выход, г':r.yieldGrams,'Себестоимость порции':r.cost,Статус:r.status,Покрытие:r.coverage}));const ordered=[...dishes].sort((a,b)=>(b.cost||0)-(a.cost||0)),p=pages(ordered);
 return title+`<div class="kpi-grid">${kpi('Готовые блюда',money(D.ttk.dishes.length),'Полный актуальный каталог','','')}${kpi('Рассчитана себестоимость',money(D.ttk.summary.calculatedDishes),'По статусу источника','','')}${kpi('Ингредиенты и полуфабрикаты',money(D.ttk.ingredients.length),'Справочник текущих цен','','')}${kpi('Найдено по поиску',money(dishes.length),'Нажмите блюдо, чтобы открыть состав','','')}</div><div class="grid">${panel('Самые затратные порции','Топ-8 в выбранном каталоге · ₽ на порцию',barList(ordered.filter(r=>r.cost!=null).map(r=>({label:r.name,value:r.cost})),{maxRows:8}),'span6')}${panel('Как читать себестоимость','Рецептура → ингредиенты → стоимость порции',`<div class="explain-flow"><div><b>01</b><span>Количество в рецептуре<small>Учитывается единица измерения</small></span></div><div><b>02</b><span>Цена ингредиента / полуфабриката<small>Выбранная цена из текущего справочника</small></span></div><div><b>03</b><span>Стоимость готовой порции<small>Сумма строк выбранной технологической карты</small></span></div></div><p class="small muted table-foot">Неизвестная цена или количество — причина проверки, а не нулевая стоимость. Нажатие на блюдо открывает расчёт и ссылку на источник.</p>`,'span6')}${panel('Каталог блюд','Сортировка по себестоимости порции · цены не являются ценами продажи',tableHTML([{label:'Блюдо',render:r=>`<button class="row-link" data-dish="${r.id}">${esc(r.name)} ↗</button><div class="secondary">ТТК № ${r.id}</div>`},{label:'Выход, г',numeric:true,render:r=>money(r.yieldGrams)},{label:'Порция, ₽',numeric:true,render:r=>`<b>${exact(r.cost)}</b>`},{label:'Покрытие',numeric:true,render:r=>percent(r.coverage)},{label:'Статус',render:r=>`<span class="status ${r.status==='РАССЧИТАНО'?'paid':'debt'}">${esc(r.status)}</span>`}],p.rows)+p.footer,'span12')}</div>`;
}
function openDish(id){const dish=D.ttk.dishes.find(d=>d.id===+id);if(!dish)return;const rows=D.ttk.recipes.filter(r=>r.dishId===dish.id);const quant=n=>n==null?'—':n.toLocaleString('ru-RU',{maximumFractionDigits:5});modal(`${dish.name} · ТТК № ${dish.id}`,`<div class="detail-kpis">${kpi('Себестоимость порции',exact(dish.cost))}${kpi('Выход',money(dish.yieldGrams),'','','г')}${kpi('Покрытие',percent(dish.coverage),'','','')}</div>`+tableHTML([{label:'Ингредиент',key:'name'},{label:'Количество',numeric:true,render:r=>quant(r.quantity)},{label:'Единица',key:'unit'},{label:'Цена, ₽',numeric:true,render:r=>exact(r.price)},{label:'Стоимость, ₽',numeric:true,render:r=>exact(r.cost)},{label:'Статус',key:'status'}],rows)+`<p class="small table-foot">Сумма строк: <b>${exact(sum(rows.map(r=>r.cost)))} ₽</b> · ${sourceLink('ttk',dish.sourceCell,'Исходная карточка')}</p><div class="dialog-actions"><button class="button" id="detail-export">↓ Выгрузить состав</button></div>`);$('#detail-export').onclick=()=>exportCSV(rows.map(r=>({Блюдо:dish.name,Ингредиент:r.name,Количество:r.quantity,Единица:r.unit,Цена:r.price,Стоимость:r.cost,Статус:r.status})),'recipe')}

function bindViews(){
 $$('[data-view-key]').forEach(b=>b.onclick=()=>{state[b.dataset.viewKey]=b.dataset.view;state.page=1;render()});$$('[data-state]').forEach(s=>s.onchange=()=>{state[s.dataset.state]=s.value;state.page=1;render()});
 $$('[data-search]').forEach(input=>input.oninput=()=>{const key=input.dataset.search,pos=input.selectionStart;state[key]=input.value;state.page=1;render();const el=$(`[data-search="${key}"]`);el.focus();el.setSelectionRange(pos,pos)});
 $$('[data-page]').forEach(b=>b.onclick=()=>{state.page=+b.dataset.page;render()});$('#all-articles')?.addEventListener('change',e=>{state.allArticles=e.target.checked;render()});$$('[data-pnl-table]').forEach(b=>b.onclick=()=>{state.pnlView='table';render();window.scrollTo({top:0})});
 $$('[data-person]').forEach(b=>b.onclick=()=>openPerson(b.dataset.person));$$('[data-dish]').forEach(b=>b.onclick=()=>openDish(b.dataset.dish));$$('[data-supplier-row]').forEach(b=>b.onclick=()=>openSupplier(b.dataset.supplierRow));
}
function bindCommon(){
 $('#month')?.addEventListener('change',e=>{state.months[state.tab]=+e.target.value;state.page=1;render()});$('#entity')?.addEventListener('change',e=>{state.entity=e.target.value;render()});
 $$('[data-scope]').forEach(b=>b.onclick=()=>{state.scopes[state.tab]=b.dataset.scope;state.page=1;render()});$$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;render()});
 $$('[data-open-entity]').forEach(b=>b.onclick=()=>{state.entity=b.dataset.openEntity;state.tab='pnl';state.months.pnl=state.months.overview;state.scopes.pnl=state.scopes.overview;render();window.scrollTo({top:0})});
 $$('[data-open-sources]').forEach(b=>b.onclick=openSources);$('#export-button')?.addEventListener('click',()=>exportCSV(currentExport));
}
function render(){if(!D)return;const groups=[['Обзор',['overview']],['Финансы',['pnl','cash']],['Обязательства',['salary','suppliers']],['Аналитика',['ttk']]];$('#navigation').innerHTML=groups.map(([label,ids])=>`<div class="side-caption">${label}</div>`+tabDefs.filter(t=>ids.includes(t[0])).map(([id,label,path])=>`<button class="nav-button ${state.tab===id?'active':''}" data-tab="${id}" ${state.tab===id?'aria-current="page"':''}>${icon(path)}<span>${label}</span></button>`).join('')).join('');$('#crumb-title').textContent=tabDefs.find(t=>t[0]===state.tab)[1];$('#page').innerHTML=({overview:renderOverviewV2,pnl:renderPnl,cash:renderCash,salary:renderSalary,suppliers:renderSuppliers,ttk:renderTtk}[state.tab])();const f=$('#page .filters');$('#global-filters').innerHTML='';if(f)$('#global-filters').append(f);$('#page').classList.toggle('plan-mode',['overview','pnl'].includes(state.tab)&&state.mode==='plan');$$('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.page=1;render();window.scrollTo({top:0})});$('#footer-update').textContent=`Снимок данных: ${datetime(D.generatedAt)}`;$('#strip-update').textContent=datetime(D.generatedAt);$('#source-chips').innerHTML=Object.values(D.sources).map(s=>`<button class="source-chip ${['salary','ttk','opiu'].includes(s.key)?'warn':''}" data-open-sources><i></i>${esc(s.label)} <span>· ${date(s.modifiedAt)}</span></button>`).join('');bindCommon();bindViews();bindComparison();bindChartTooltips();}
function openSources(){let body=Object.values(D.sources).map(s=>`<section class="source-card"><h3>${esc(s.label)}</h3><p>${esc(s.detail)}</p><dl><dt>Изменение файла</dt><dd>${datetime(s.modifiedAt)}</dd><dt>Загрузка в кабинет</dt><dd>${datetime(s.fetchedAt)}</dd><dt>Покрытие</dt><dd>${s.coverage.map(p=>`${shortMonths[+p.slice(5)-1]} ${p.slice(0,4)}`).join(', ')||'Текущий справочник'}</dd>${s.lastOperationDate?`<dt>Последняя операция</dt><dd>${date(s.lastOperationDate,true)}</dd>`:''}</dl>${sourceLink(s.key)}</section>`).join('');body+=`<details><summary>Контроль модели ОПиУ</summary><div class="table-wrap"><table class="data-table"><tbody>${D.pnl.checks.map(c=>`<tr><td>${esc(c.label)}</td><td>${esc(c.status)}</td><td class="number">${exact(c.value)}</td></tr>`).join('')}</tbody></table></div></details><details><summary>Вопросы к данным зарплат · ${D.salary.issues.length}</summary><div>${D.salary.issues.map(i=>`<p class="small"><b>${esc(i.title)}</b> · ${i.amount!=null?money(i.amount)+' ₽ · ':''}${esc(i.detail)}<br>${sourceLink('salary',i.cell,i.cell)}</p>`).join('')}</div></details><details><summary>Правила расчётов</summary><div><p class="small muted">ОПиУ и ДДС используют разные принципы: начисления и движение денег. АУП уже включён в статьи и повторно к расходам не прибавляется. Остатки по кошелькам проверены по формуле «начало + все движения = конец».</p><p class="small muted">Зарплаты: зелёный итог — выплачено, незелёный — к выплате. Графики относятся к календарным датам смен, а не к дате банковского платежа. Недельные итоги распределены по месяцам пропорционально дневным значениям. Суммы без имени и формулы с повторным итогом вынесены на проверку. Долг поставщикам определяется заливкой документов, а не датой оплаты.</p></div></details>`;modal('Источники и актуальность',body)}
function exportCSV(rows,name=state.tab){if(!rows.length){toast('Нет строк для выгрузки.');return}const columns=[...new Set(rows.flatMap(r=>Object.keys(r)))],cell=v=>'"'+String(v??'').replace(/"/g,'""').replace(/^[=+@-]/,"'$&")+'"';const csv='\uFEFF'+[columns.map(cell).join(';'),...rows.map(r=>columns.map(c=>cell(r[c])).join(';'))].join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`ВИДИМ-ДЕНЬГИ-${name}-${D.asOf}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function bindComparison(){
 $('#presentation')?.addEventListener('change',e=>{state.mode=e.target.value;render()});$('#scope-select')?.addEventListener('change',e=>{state.scopes[state.tab]=e.target.value;state.page=1;render()});
 $$('[data-jump]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.jump;state.page=1;render();window.scrollTo({top:0})});
 $('a.brand[href="#overview"]').onclick=e=>{e.preventDefault();state.tab='overview';render();window.scrollTo({top:0})};
}
function bindChartTooltips(){
 let tip=$('#chart-tip');if(!tip){tip=document.createElement('div');tip.id='chart-tip';tip.className='chart-tooltip';tip.hidden=true;document.body.append(tip)}tip.hidden=true;
 $$('.chart-point').forEach(el=>{const show=e=>{const text=el.querySelector('title')?.textContent;if(!text)return;tip.textContent=text;tip.hidden=false;const r=el.getBoundingClientRect(),x=e.clientX||r.x+r.width/2,y=e.clientY||r.y;tip.style.left=Math.max(8,Math.min(x+10,window.innerWidth-tip.offsetWidth-10))+'px';tip.style.top=Math.max(8,Math.min(y-45,window.innerHeight-tip.offsetHeight-10))+'px'};el.addEventListener('pointermove',show);el.addEventListener('focus',show);el.addEventListener('pointerleave',()=>tip.hidden=true);el.addEventListener('blur',()=>tip.hidden=true)});
}
new ResizeObserver(()=>document.documentElement.style.setProperty('--top-height',$('#top-stack').getBoundingClientRect().height+'px')).observe($('#top-stack'));
const bytes = b64 => Uint8Array.from(atob(b64),c=>c.charCodeAt(0));
async function envelope(){const r=await fetch('./data/snapshot.enc.json',{cache:'no-store'});if(!r.ok)throw new Error('Данные пока не опубликованы.');const e=await r.json();if(e.format!=='wsm-aes-gcm-v1'||e.kdf!=='PBKDF2-SHA256'||e.iterations<600000||e.iterations>2000000)throw new Error('Не удалось проверить формат данных.');return e}
async function decrypt(e,key){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(e.iv),additionalData:new TextEncoder().encode('WSM_FINANCE_V1')},key,bytes(e.ciphertext));let decoded=plain;if(e.compression==='gzip')decoded=await new Response(new Blob([plain]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();else if(e.compression)throw new Error('Неизвестный формат сжатия.');return JSON.parse(new TextDecoder().decode(decoded))}
async function unlock(password){const e=await envelope(),material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:bytes(e.salt),iterations:e.iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']);const data=await decrypt(e,key);sessionKey=key;sessionSalt=e.salt;activate(data)}
function activate(data){if(data.schemaVersion!==1)throw new Error('Неподдерживаемая версия отчёта.');D=data;state.months.overview=state.months.pnl=D.defaultMonth;state.months.cash=D.cash.months.filter(m=>m.hasData).at(-1)?.month??D.defaultMonth;state.months.salary=+D.sources.salary.lastOperationDate?.slice(5,7)||D.defaultMonth;state.months.suppliers=+D.sources.suppliers.lastOperationDate?.slice(5,7)||D.defaultMonth;state.months.ttk=Math.max(...D.ttk.sales.map(s=>s.month),1);$('#login').hidden=true;$('#app').hidden=false;$('#password').value='';render()}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const button=$('.login-submit');button.disabled=true;$('#login-error').textContent='';try{await unlock($('#password').value)}catch(err){$('#login-error').textContent=err.name==='OperationError'?'Пароль не подошёл. Проверьте раскладку и попробуйте снова.':err.message;$('#password').select()}finally{button.disabled=false}});
$('#show-password').onclick=()=>{const p=$('#password');p.type=p.type==='password'?'text':'password';$('#show-password').setAttribute('aria-label',p.type==='password'?'Показать пароль':'Скрыть пароль')};
$('#source-button').onclick=openSources;$('#close-dialog').onclick=()=>$('#detail-dialog').close();$('#detail-dialog').addEventListener('click',e=>{if(e.target===$('#detail-dialog'))$('#detail-dialog').close()});
$('#lock-button').onclick=()=>{D=null;sessionKey=null;sessionSalt=null;currentExport=[];$('#page').innerHTML='';$('#dialog-body').innerHTML='';$('#dialog-title').textContent='';$('#detail-dialog').close();$('#global-filters').innerHTML='';$('#source-chips').innerHTML='';if($('#chart-tip'))$('#chart-tip').hidden=true;state.salarySearch=state.supplierSearch=state.articleSearch=state.ttkSearch='';$('#app').hidden=true;$('#login').hidden=false;$('#password').focus()};
$('#refresh-button').onclick=async()=>{const b=$('#refresh-button');b.disabled=true;try{let data;if(preview){const r=await fetch('/__preview-data',{cache:'no-store'});data=await r.json()}else{const e=await envelope();if(e.salt!==sessionSalt)throw new Error('Пароль доступа изменён. Закройте кабинет и войдите заново.');data=await decrypt(e,sessionKey)}const changed=data.generatedAt!==D.generatedAt;D=data;render();toast(changed?'Данные кабинета обновлены.':'У вас последняя сохранённая версия данных.')}catch(e){toast(e.message||'Не удалось обновить данные.')}finally{b.disabled=false}};
if(['127.0.0.1','localhost'].includes(location.hostname)&&new URL(location.href).searchParams.get('preview')==='1'){preview=true;fetch('/__preview-data',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Предпросмотр недоступен');return r.json()}).then(activate).catch(e=>$('#login-error').textContent=e.message)}
